namespace Belin.Sql.Reflection;

using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;

/// <summary>
/// Provides information about a database column.
/// </summary>
public sealed class ColumnInfo {

	/// <summary>
	/// The nullability context.
	/// </summary>
	private static readonly ThreadLocal<NullabilityInfoContext> nullabilityContext = new(() => new NullabilityInfoContext());

	/// <summary>
	/// Value indicating whether the column can be read.
	/// </summary>
	public bool CanRead => property.CanRead;

	/// <summary>
	/// Value indicating whether the column can be written to.
	/// </summary>
	public bool CanWrite => property.CanWrite;

	/// <summary>
	/// Value indicating whether the column value is generated by the database.
	/// </summary>
	public bool IsComputed { get; }

	/// <summary>
	/// Value indicating whether the column value is generated by the database when a row is inserted.
	/// </summary>
	public bool IsIdentity { get; }

	/// <summary>
	/// Value indicating whether the column value is nullable.
	/// </summary>
	public bool IsNullable { get; }

	/// <summary>
	/// The column name.
	/// </summary>
	public string Name { get; }

	/// <summary>
	/// The type of the column value.
	/// </summary>
	public Type Type => property.PropertyType;

	/// <summary>
	/// The property information providing the column metadata.
	/// </summary>
	private readonly PropertyInfo property;

	/// <summary>
	/// Creates new column information.
	/// </summary>
	/// <param name="property">The property information providing the column metadata.</param>
	public ColumnInfo(PropertyInfo property) {
		this.property = property;

		var databaseGeneratedOption = property.GetCustomAttribute<DatabaseGeneratedAttribute>()?.DatabaseGeneratedOption ?? DatabaseGeneratedOption.None;
		IsComputed = databaseGeneratedOption != DatabaseGeneratedOption.None;
		IsIdentity = databaseGeneratedOption == DatabaseGeneratedOption.Identity;
		IsNullable = Nullable.GetUnderlyingType(property.PropertyType) is not null || nullabilityContext.Value!.Create(property).WriteState != NullabilityState.NotNull;
		Name = property.GetCustomAttribute<ColumnAttribute>()?.Name ?? property.Name;
	}

	/// <summary>
	/// Gets the property value of a specified object.
	/// </summary>
	/// <param name="instance">The object whose property value will be returned.</param>
	/// <returns>The property value of the specified object.</returns>
	public object? GetValue<T>(T instance) where T: new() => property.GetValue(instance);

	/// <summary>
	/// Sets the property value of a specified object.
	/// </summary>
	/// <param name="instance">The object whose property value will be set.</param>
	/// <param name="value">The new property value.</param>
	public void SetValue<T>(T instance, object? value) where T: new() => property.SetValue(instance, value);
}
