namespace Belin.Sql;

using DataType = System.Data.DbType;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;

/// <summary>
/// Provides information about a database column.
/// </summary>
public sealed class DbColumnInfo {

	/// <summary>
	/// The nullability context.
	/// </summary>
	private static readonly ThreadLocal<NullabilityInfoContext> nullabilityContext = new(() => new NullabilityInfoContext());

	/// <summary>
	/// The mapping between common .NET types and data types.
	/// </summary>
	private static readonly Dictionary<Type, DataType> typeMap = new() {
		[typeof(bool?)] = DataType.Boolean,
		[typeof(bool)] = DataType.Boolean,
		[typeof(byte?)] = DataType.Byte,
		[typeof(byte)] = DataType.Byte,
		[typeof(byte[])] = DataType.Binary,
		[typeof(char?)] = DataType.StringFixedLength,
		[typeof(char)] = DataType.StringFixedLength,
		[typeof(DateOnly?)] = DataType.Date,
		[typeof(DateOnly)] = DataType.Date,
		[typeof(DateTime?)] = DataType.DateTime,
		[typeof(DateTime)] = DataType.DateTime,
		[typeof(DateTimeOffset?)] = DataType.DateTimeOffset,
		[typeof(DateTimeOffset)] = DataType.DateTimeOffset,
		[typeof(decimal?)] = DataType.Decimal,
		[typeof(decimal)] = DataType.Decimal,
		[typeof(double?)] = DataType.Double,
		[typeof(double)] = DataType.Double,
		[typeof(float?)] = DataType.Single,
		[typeof(float)] = DataType.Single,
		[typeof(Guid?)] = DataType.Guid,
		[typeof(Guid)] = DataType.Guid,
		[typeof(int?)] = DataType.Int32,
		[typeof(int)] = DataType.Int32,
		[typeof(long?)] = DataType.Int64,
		[typeof(long)] = DataType.Int64,
		[typeof(sbyte?)] = DataType.SByte,
		[typeof(sbyte)] = DataType.SByte,
		[typeof(short?)] = DataType.Int16,
		[typeof(short)] = DataType.Int16,
		[typeof(string)] = DataType.String,
		[typeof(TimeOnly?)] = DataType.Time,
		[typeof(TimeOnly)] = DataType.Time,
		[typeof(uint?)] = DataType.UInt32,
		[typeof(uint)] = DataType.UInt32,
		[typeof(ulong?)] = DataType.UInt64,
		[typeof(ulong)] = DataType.UInt64,
		[typeof(ushort?)] = DataType.UInt16,
		[typeof(ushort)] = DataType.UInt16
	};

	/// <summary>
	/// Value indicating whether the column can be read.
	/// </summary>
	public bool CanRead => property.CanRead;

	/// <summary>
	/// Value indicating whether the column can be written to.
	/// </summary>
	public bool CanWrite => property.CanWrite;

	/// <summary>
	/// The SQL data type of the column.
	/// </summary>
	public DataType DbType { get; }

	/// <summary>
	/// Value indicating whether the column value is generated by the database.
	/// </summary>
	public bool IsComputed { get; }

	/// <summary>
	/// Value indicating whether the column value is generated by the database when a row is inserted.
	/// </summary>
	public bool IsIdentity { get; }

	/// <summary>
	/// Value indicating whether the column value is nullable.
	/// </summary>
	public bool IsNullable { get; }

	/// <summary>
	/// The column name.
	/// </summary>
	public string Name { get; }

	/// <summary>
	/// The type of the column value.
	/// </summary>
	public Type PropertyType => property.PropertyType;

	/// <summary>
	/// The property information providing the column metadata.
	/// </summary>
	private readonly PropertyInfo property;

	/// <summary>
	/// Creates new column information.
	/// </summary>
	/// <param name="property">The property information providing the column metadata.</param>
	public DbColumnInfo(PropertyInfo property) {
		this.property = property;

		var column = property.GetCustomAttribute<ColumnAttribute>();
		Name = column?.Name ?? property.Name;
		DbType = true switch {
			true when string.IsNullOrWhiteSpace(column?.TypeName) => typeMap.TryGetValue(property.PropertyType, out var dbType) ? dbType : DataType.Object,
			true when Enum.TryParse<DataType>(column.TypeName, ignoreCase: true, out var dbType) => dbType,
			_ => DataType.Object
		};

		var databaseGeneratedOption = property.GetCustomAttribute<DatabaseGeneratedAttribute>()?.DatabaseGeneratedOption ?? DatabaseGeneratedOption.None;
		IsComputed = databaseGeneratedOption != DatabaseGeneratedOption.None;
		IsIdentity = databaseGeneratedOption == DatabaseGeneratedOption.Identity;
		IsNullable = Nullable.GetUnderlyingType(property.PropertyType) is not null || nullabilityContext.Value!.Create(property).WriteState != NullabilityState.NotNull;
	}

	/// <summary>
	/// Gets the property value of a specified object.
	/// </summary>
	/// <param name="instance">The object whose property value will be returned.</param>
	/// <returns>The property value of the specified object.</returns>
	public object? GetValue<T>(T instance) where T: new() => property.GetValue(instance);

	/// <summary>
	/// Sets the property value of a specified object.
	/// </summary>
	/// <param name="instance">The object whose property value will be set.</param>
	/// <param name="value">The new property value.</param>
	public void SetValue<T>(T instance, object? value) where T: new() => property.SetValue(instance, value);
}
